### ISSUE TITLE
نمایشگر بازی

### ISSUE THREAD

**Issue by arghv** [SharifAIChallenge/AIC18-Client-Python#1]
خروجی گیم کلاینت پایتون در نمایشگر بازی تو نوبت های اول گیر میکنه ولی خروجی کلاینت جاوا به خوبی اجرا می 
شود
کلاینت پایتون فایل گیم 
را خراب میکنه و در نمایشگر اجرا نمیشه
[Game.txt](https://github.com/SharifAIChallenge/AIC18-Client-Python/files/1702475/Game.txt)
[client.log](https://github.com/SharifAIChallenge/AIC18-Client-Python/files/1702479/client.log)
[Game.txt](https://github.com/SharifAIChallenge/AIC18-Client-Python/files/1702535/Game.txt)

**Comment by artajmir3** [comment]
سلام
ضمن تشکر از توجهتون به اشکالات و اعلام آن‌‌ها این مشکل ناشی از نمایشگر بازی بود که در نسخه جدید آن رفع شد
