### ISSUE TITLE
pass statements!

### ISSUE THREAD

**Issue by MrRezaei** [SharifAIChallenge/AIC18-Client-Python#2]
We Don't Understand Why Python Client Would Have **Empty Methods** Containing Only pass Statements!
```
    def get_damage(self, lvl=None):
        pass

    def get_price(self, lvl=None):
        pass

    def get_attack_range(self, lvl=None):
        pass

    def get_attack_speed(self):
        pass
```
Can Someone Explain...?

**Comment by kiarash96** [comment]
Because these methods have polymorphic behavior and therefore are abstract. They are implemented accordingly in the sub-classes. (In this case `CannonTower` and `ArcherTower` classes)
